# Generated by Django 3.2.9 on 2022-03-08 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20220308_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='id',
            new_name='listing_id',
        ),
    ]
