# Generated by Django 3.2.9 on 2022-03-22 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='auction',
            new_name='listing',
        ),
    ]
