# Generated by Django 3.2.9 on 2022-03-22 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_auction_watchlist_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='listing',
            new_name='listing_id',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='user',
            new_name='user_id',
        ),
    ]
